include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_print: false  
    unused_local_variable: ignore
    invalid_use_of_protected_member: ignore
  analyzer:
  errors:
    unused_local_variable: ignore
    invalid_use_of_protected_member: ignore