name: hyper_ui
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.0.4
  file_picker: ^8.0.7
  uuid: ^4.0.0
  flutter_image_compress: ^2.0.3
  cached_network_image: ^3.2.2
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  flutter_map: ^7.0.2
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.6
  blur: ^4.0.0
  flutter_svg: ^2.0.5
  custom_clippers: ^2.0.0
  badges: ^3.1.1
  flutter_markdown: ^0.7.3+1
  dotted_border: ^2.0.0+3
  faker_dart: ^0.2.1
  syncfusion_flutter_charts: ^26.2.9
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11
  flutter_animate: ^4.1.1+1
  dio: ^5.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_inappwebview: ^5.7.2+3
  syncfusion_flutter_calendar: ^26.2.9
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  numberpicker: ^2.1.2
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.2.0
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/new_logo.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
 